WEB_CLIENT_ID = "web_client_id"
IOS_CLIENT_ID = "ios_client_id"
ANDROID_CLIENT_ID = "android_client_id"
ANDROID_AUDIENCE = WEB_CLIENT_ID

CLIENT_IDS = [WEB_CLIENT_ID, IOS_CLIENT_ID, ANDROID_CLIENT_ID]

AUDIENCES = [ANDROID_AUDIENCE]